# Generated by Django 6.0.4 on 2026-05-14 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Blood', 'Blood'), ('Urine', 'Urine'), ('Scan', 'Scan'), ('Other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_ranges', models.TextField()),
                ('sample_type', models.CharField(choices=[('Blood', 'Blood'), ('Urine', 'Urine'), ('Saliva', 'Saliva'), ('Other', 'Other')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField()),
                ('patient_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('lab_test_value', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('prescribed_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtech.labtest')),
            ],
        ),
    ]
