# Generated by Django 6.0.5 on 2026-05-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_patient_membership_id_patient_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='emp_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
