# Generated by Django 6.0.5 on 2026-05-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_staff_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
